### ISSUE TITLE
Space Age compatibility

### ISSUE THREAD

**Issue by hurricup** [NoxyNixie/Noxys_Trees#13]
Is mod going to be updated for SA?

**Comment by NoxyNixie** [comment]
Absolutely but I've been very busy with real life. I got SA yesterday from a friend and will likely spin it up this weekend.

**Comment by hurricup** [comment]
Let me know if I can help

**Comment by NoxyNixie** [comment]
Fixed right?

**Comment by hurricup** [comment]
yep. played yesterday, was fine. will get back if smth breaks

**Comment by hurricup** [comment]
why didn't you want major version to match factorio major version?

**Comment by NoxyNixie** [comment]
Because that is simply not the system I'm using.
