### ISSUE TITLE
nature is taking industry back.

### ISSUE THREAD

**Issue by Technickfreak** [NoxyNixie/Noxys_Trees#6]
can trees destroy buildings?

if not can you build something like that?
for example that 1 tree destroyed a building after 100 years.
and that 10 trees destroyed a building after 10 years

nature is taking industry back.

so the forgotten bases remain forgotten.

**Comment by NoxyNixie** [comment]
I've had an idea like that on my shelves for a while now but it won't be part of this mod (it is just outside of its scope). If I have some more spare time I might actually get to making that mod idea a reality.

However it won't be part of this mod so closing the issue ;)
