### ISSUE TITLE
Changelog stops at version 0.3.1

### ISSUE THREAD

**Issue by Be-Cool-Man** [NoxyNixie/Noxys_Trees#7]
I found out by chance that the changelog hasn't had any new entries since version 0.3.1. Since the mod is already at version 0.4.2, I wanted to ask why the changelogs are no longer maintained.

**Comment by NoxyNixie** [comment]
Here is the changelog: https://github.com/NoxyNixie/Noxys_Trees/commits/master

Here: https://mods.factorio.com/mod/Noxys_Trees/discussion/5edf8a55f44373000e20bfb0 , are more detailed thoughts on the changelog and it also has the reasons why I don't really update them if I ever made one.

Also nothing major has change so I could argue that it hasn't needed an update.

You can send a PR to update the changelog if you so desire but I have no plans to update it myself.
