### ISSUE TITLE
Incompatibility with IR3

### ISSUE THREAD

**Issue by klugemonkey** [NoxyNixie/Noxys_Trees#8]
There are some specific trees in IR3 ("-planted") that are added that appear to be automatically replanted by Noxy's trees resulting in trees that can not be selected and removed by the player.   

I you would please confirm this incompatibility with IR3 and add the tree prototypes to the noxy_trees.disabled table, so as to avoid being marked as incompatible, it would be much appreciated.  

Factorio 1.1.76
IR3 3.0.14
Noxys Trees 0.4.2

**Comment by NoxyNixie** [comment]
Fixed in 0.4.3.
